version: 2
registries:
  npm:
    type: npm-registry
    url: https://registry.npmjs.org/
  github:
    type: npm-registry
    url: https://npm.pkg.github.com/
    token: ${{ secrets.DEPENDABOT_TOKEN }}

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    registries:
      - npm
      - github
    target-branch: develop
    labels:
      - dependencies
    commit-message:
      prefix: chore(dependencies)

