version: 2
registries:
  github:
    type: npm-registry
    url: https://npm.pkg.github.com/
    token: ${{ secrets.DEPENDABOT_TOKEN }}
    replaces-base: false

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    registries:
      - github
    target-branch: develop
    labels:
      - dependencies
    commit-message:
      prefix: chore(dependencies)

