name: Prepare Node

inputs:
  path:
    required: true
    type: string
  npm-token:
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 18.15.0
        cache: npm
        registry-url: https://npm.pkg.github.com/
        scope: '@a11yphant'
        cache-dependency-path: ${{ inputs.path }}/package-lock.json

    - name: NPM Install
      shell: bash
      run: npm ci --prefix ${{ inputs.path }}
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm-token }}
