name: Prepare Node

inputs:
  path:
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc
        cache: npm
        cache-dependency-path: ${{ inputs.path }}/package-lock.json

    - name: NPM Install
      shell: bash
      run: npm ci --prefix ${{ inputs.path }}
