name: Prepare Node

inputs:
  path:
    required: true
    type: string

runs:
  using: composite
  steps:
    prepare:
      runs-on: ubuntu-latest
      permissions:
        contents: read
        packages: read
      steps:
        - name: Setup node
          uses: actions/setup-node@v3
          with:
            node-version: 14
            cache: npm
            registry-url: https://npm.pkg.github.com/
            scope: '@a11yphant'

        - name: NPM Install
          run: npm ci --prefix ${{ inputs.path }}
          env:
            NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}