version: "3"

services:
  selenium:
    image: ${SELENIUM_IMAGE:-selenium/standalone-chrome:4}
    restart: always
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - 4444:4444

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: a11yphant
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: a11yphant
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  rabbitmq:
    image: rabbitmq:management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: secret
    volumes:
      - ./docker/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
      - ./docker/rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
    ports:
      - 15672:15672
      - 5672:5672

  mailhog:
    image: mailhog/mailhog
    restart: unless-stopped
    ports:
      - 1025:1025
      - 8025:8025

volumes:
  postgres_data:
