version: "3"

services:
  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: a11yphant
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: a11yphant
      POSTGRES_HOST: 0.0.0.0
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: pg_isready -q -d a11yphant -U a11yphant
      timeout: 45s
      interval: 10s
      retries: 10

  mailhog:
    image: mailhog/mailhog
    restart: unless-stopped
    ports:
      - 1025:1025
      - 8025:8025

volumes:
  postgres_data:
