version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-5e4265rbk7zw"
region = "eu-central-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
