AWSTemplateFormatVersion: 2010-09-09

Description: >-
  a11y-challenges

Transform: AWS::Serverless-2016-10-31

Globals:
    Function:
        Timeout: 60

Parameters:
  StageName:
    Type: String
    Default: Production

Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref StageName

  GraphQLApiFunction:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: graphql-api
      CodeUri: services/api
      Handler: entrypoint.handle
      Runtime: nodejs12.x
      Environment:
        Variables:
          NODE_ENV: 'production'
          API_LAMBDA: 1
          API_GRAPHQL_DEBUG: 1
          API_GRAPHQL_PLAYGROUND: 1
          API_GRAPHQL_SCHEMA_INTROSPECTION: 1
      Events:
        GraphqlGet:
          Type: Api 
          Properties:
            Path: /graphql
            Method: get
            RestApiId: !Ref ApiGateway
        GraphqlPost:
          Type: Api
          Properties:
            Path: /graphql
            Method: post
            RestApiId: !Ref ApiGateway

Outputs:
    GraphQLApi:
        Description: GraphQL API entrypoint
        Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${StageName}"
