AWSTemplateFormatVersion: 2010-09-09

Description: >-
  a11y-challenges

Transform: AWS::Serverless-2016-10-31

Globals:
    Function:
        Timeout: 60

Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: 'production'

  GraphQLApiFunction:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: graphql-api
      CodeUri: services/api
      Handler: entrypoint.handle
      Runtime: nodejs12.x
      Environment:
        Variables:
          API_LAMBDA: 1
          API_GRAPHQL_DEBUG: 1
          API_GRAPHQL_PLAYGROUND: 1
      Events:
        GraphqlGet:
          Type: Api 
          Properties:
            Path: /graphql
            Method: get
        GraphqlPost:
          Type: Api
          Properties:
            Path: /graphql
            Method: post

Outputs:
    GraphQLApi:
        Description: GraphQL API entrypoint
        Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/"
