name: Variables

outputs:
  environment-name:
    description: Environment Name
    value: ${{ steps.environment-name.outputs.environment-name }}

run:
  using: composite
  steps:
    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v4

    - run: echo "environment-name=${{ env.GITHUB_REF_SLUG }}" >> $GITHUB_OUTPUT
      id: environment-name
