#----------------------------------------------------------------------
#
# Rules
#
#----------------------------------------------------------------------

.api_rules: &api_rules
  if: ($CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "develop" || $CI_PIPELINE_SOURCE == "merge_request_event")
  changes:
    - services/api/**/*


.site_rules: &site_rules
  if: ($CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "develop" || $CI_PIPELINE_SOURCE == "merge_request_event")
  changes:
    - services/site/**/*

.submission-checker_rules: &submission-checker_rules
  if: ($CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "develop" || $CI_PIPELINE_SOURCE == "merge_request_event")
  changes:
    - services/submission-checker/**/*