name: Docker Publish Image From Artifact

inputs:
  artifact-name:
    required: true
    type: string
  image:
    required: true
    type: string
  registry-user:
    required: true
    type: string
  registry-password:
    required: true
    type: string

outputs:
  digest:
    description: "Docker Image Digest"
    value: ${{ steps.digest.outputs.digest }}

runs:
  using: composite
  steps:
    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ inputs.registry-user }}
        password: ${{ inputs.registry-password }}

    - name: Get Artifact
      uses: actions/download-artifact@v2
      with:
        name: ${{ inputs.artifact-name }}
        path: /tmp/${{ inputs.artifact-name }}/

    - name: Load Image
      shell: bash
      run: docker load --input /tmp/${{ inputs.artifact-name }}/image.tar

    - name: Push Image
      shell: bash
      run: docker push ${{ inputs.image }}

    - name: Set Digest as output
      id: digest
      shell: bash
      run: |
        DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' ${{ inputs.image }})
        echo "digest=${DIGEST: -71}" >> $GITHUB_OUTPUT
