.deploy:
  tags:
    - docker
  stage: deploy
  needs:
    - build:prisma
    - production-dependencies:prisma
    - build:api
    - production-dependencies:database-migration
    - build:site
    - production-dependencies:site
    - build:import-challenges
    - production-dependencies:import-challenges
    - build:submission-checker
    - production-dependencies:submission-checker
    - build:submission-renderer
    - production-dependencies:submission-renderer
  image: registry.gitlab.com/gitlab-org/terraform-images/stable:latest
  cache: {} # disable cache
  variables:
    TF_IN_AUTOMATION: 1
  before_script:
    - apk update
    - apk add zip
    - terraform -chdir=terraform/cloud init
  script:
    - terraform -chdir="terraform/cloud" workspace new $WORKSPACE || echo ""
    - terraform -chdir=terraform/cloud workspace select $WORKSPACE
    - terraform -chdir=terraform/cloud apply -auto-approve -var="postgres_cluster_root_password=$TF_PROD_POSTGRES_CLUSTER_ROOT_PASSWORD" -var="gitlab_ci_registery_user=$CI_REGISTRY_USER" -var="gitlab_ci_registry_password=$CI_REGISTRY_PASSWORD" -var="heroku_registry_password=$HEROKU_AUTH_TOKEN"