.test:
  tags:
    - docker
  stage: test
  image: node:14-alpine
  script: npm run test:coverage --prefix $PROJECT_PATH -- --runInBand --verbose
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - $PROJECT_PATH/junit.xml
    reports:
        junit: $PROJECT_PATH/junit.xml
        coverage_report:
          coverage_format: cobertura
          path: $PROJECT_PATH/coverage/cobertura-coverage.xml
  coverage: '/^Lines\s*:\s*([^%]+)/'
