.production-dependencies:
  tags:
    - docker
  stage: build
  image:
    name: public.ecr.aws/lambda/nodejs:12
    entrypoint: [""]
  before_script:
    - echo "//gitlab.mediacube.at/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
    - echo "//gitlab.mediacube.at/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> $PROJECT_PATH/.npmrc
  cache:
    key: ${CI_COMMIT_REF_SLUG}-cent-os
    paths:
      - .npm-cent-os
  script:
    - npm ci --production --prefix $PROJECT_PATH --cache .npm-cent-os
    - find $PROJECT_PATH/* -mtime +10950 -exec touch {} \; # search for files with corrupt timestamps and update them
  artifacts:
    paths:
      - $PROJECT_PATH/node_modules
    expire_in: 1 day
