.npm-dependencies:
  tags:
    - docker
  stage: prepare
  image: node:14-alpine
  script: npm install --prefix $PROJECT_PATH
  artifacts:
    paths:
      - $PROJECT_PATH/node_modules
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
    - if: '$CI_COMMIT_BRANCH == "develop"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'