.lint:
  tags:
    - docker
  stage: analyze
  image: node:14-alpine
  script: npm run lint --prefix $PROJECT_PATH
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
    - if: '$CI_COMMIT_BRANCH == "develop"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'