.build:site:
  extends:
    - .build
  needs:
    - generate-graphql-schema:api
    - test:site
  variables:
    PROJECT_PATH: services/site
    IMAGE_NAME_APP: a11yphant/a11yphant/site
    IMAGE_APP: $CI_REGISTRY/$IMAGE_NAME_APP:$CI_COMMIT_REF_SLUG
  script:
    - docker pull $IMAGE_APP || (docker pull $CI_REGISTRY/$IMAGE_NAME_APP && docker tag $CI_REGISTRY/$IMAGE_NAME_APP $IMAGE_APP || echo "")
    - docker build . 
        -f $PROJECT_PATH/Dockerfile 
        -t $IMAGE_APP 
        --cache-from $IMAGE_APP 
        --build-arg VERSION=$CI_COMMIT_REF_SLUG
        --build-arg SPLITBEE_TOKEN=$SPLITBEE_TOKEN
        --secret id=npmrc,src=.npmrc
    - docker push $IMAGE_APP