.deploy:
  tags:
    - docker
  stage: deploy
  needs:
    - build:api
    - production-dependencies:api
    - production-dependencies:database-migration
    - build:site
    - production-dependencies:site
    - build:import-challenges
    - production-dependencies:import-challenges
  image: registry.gitlab.com/gitlab-org/terraform-images/stable:latest
  cache: {} # disable cache
  before_script:
    - apk update
    - apk add zip
    - terraform -chdir=terraform/cloud init
    - terraform -chdir=terraform/cloud workspace select $TF_WORKSPACE
  script:
    - terraform -chdir=terraform/cloud apply
        -var="current_version=$TF_WORKSPACE"
        -var="postgres_cluster_root_user=root"
        -var="postgres_cluster_root_password=$TF_PROD_POSTGRES_CLUSTER_ROOT_PASSWORD"
        -auto-approve