.build:
  tags:
    - docker
  stage: build
  image: node:14-alpine
  script:
    - npm run build --prefix $PROJECT_PATH
    - rm -r $PROJECT_PATH/node_modules
    - npm ci --production --prefix $PROJECT_PATH
    - rm -r $PROJECT_PATH/src $PROJECT_PATH/test
  artifacts:
    paths:
      - $PROJECT_PATH
    expire_in: 1 day