name: Docker Build

inputs:
  path:
    required: true
    type: string
  npm-token:
    required: true
    type: string
  version:
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Prepare .npmrc file
      shell: bash
      run: echo "//npm.pkg.github.com/:_authToken=${{ inputs.npm-token }}" >> .npmrc

    - name: Create Cache Key
      shell: bash
      run: |
        PROJECT_PATH=${{ inputs.path }}
        PROJECT_PATH_SLUG="${PROJECT_PATH//\//-}"
        VERSION=${{ inputs.version }}
        VERSION_SLUG="${VERSION//\//-}"
        echo "CACHE_KEY=$PROJECT_PATH_SLUG-$VERSION_SLUG" >> $GITHUB_ENV

    - name: Build and Push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ${{ inputs.path }}/Dockerfile
        push: false
        build-args: |
          VERSION=${{ inputs.version }}
        secret-files: |
          npmrc=.npmrc
        cache-from: type=gha
        cache-to: type=gha,mode=max,scope=${{ env.CACHE_KEY }}
