name: Docker Build

inputs:
  path:
    required: true
    type: string
  npm-token:
    required: true
    type: string
  version:
    required: true
    type: string
  image-name:
    required: true
    type: string
  registry-user:
    required: true
    type: string
  registry-password:
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ inputs.registry-user }}
        password: ${{ inputs.registry-password }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Prepare .npmrc file
      shell: bash
      run: echo "//npm.pkg.github.com/:_authToken=${{ inputs.npm-token }}" >> .npmrc

    - name: Build and Push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ${{ inputs.path }}/Dockerfile
        push: true
        build-args: |
          VERSION=${{ inputs.version }}
        secret-files: |
          npmrc=.npmrc
        tags: ghcr.io/a11yphant/${{ inputs.image-name }}:${{ inputs.version }}-prerelease
        cache-from: type=gha
        cache-to: type=gha,mode=max,scope=${{ inputs.image-name }}-${{ inputs.version }}
