name: CI/CD

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - develop

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  variables:
    runs-on: ubuntu-22.04
    outputs:
      environment-name: ${{ steps.environment-name.outputs.environment-name }}
    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4

      - run: echo "environment-name=${{ env.GITHUB_REF_SLUG }}" >> $GITHUB_OUTPUT
        id: environment-name

  # Lint Content
  lint-content:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18.15.0
          cache: npm
          registry-url: https://npm.pkg.github.com/
          scope: '@a11yphant'
          cache-dependency-path: package-lock.json

      - name: NPM Install
        run: npm ci --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ inputs.npm-token }}

      - name: Lint Content
        run: npm run lint:content

  generate-graphql-schema:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare
        uses: ./.github/actions/prepare-node
        with:
          path: services/site
          npm-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate GraphQL Schema
        run: npm run schema:generate --prefix services/site

      - uses: actions/upload-artifact@v4
        with:
          name: graphql-schema
          path: services/site/schema.gql
          retention-days: 1

  lint-site:
    needs: generate-graphql-schema
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare
        uses: ./.github/actions/prepare-node
        with:
          path: services/site
          npm-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/download-artifact@v4
        with:
          name: graphql-schema
          path: services/site/schema.gql

      - name: Lint
        run: npm run lint --prefix services/site

  test-site:
    needs: generate-graphql-schema
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: read
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: a11yphant
          POSTGRES_USER: a11yphant
          POSTGRES_PASSWORD: secret
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    env:
      SITE_HOST: localhost
      SITE_PORT: 3001
      SITE_GRAPHQL_ENDPOINT_SERVER: http://localhost:3000/graphql
      SITE_GRAPHQL_ENDPOINT_CLIENT: http://localhost:3001/graphql
      SITE_GITHUB_LOGIN_ENDPOINT: /auth/github
      SITE_TWITTER_LOGIN_ENDPOINT: /auth/twitter
      SITE_PLAUSIBLE_BASE_URL: "https://plausible.a11yphant.com"
      SITE_BASE_URL: "http://localhost:3001"
      DATABASE_URL: postgresql://a11yphant:secret@localhost:5432/a11yphant
      DATABASE_URL_UNPOOLED: postgresql://a11yphant:secret@localhost:5432/a11yphant
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare
        uses: ./.github/actions/prepare-node
        with:
          path: services/site
          npm-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/download-artifact@v4
        with:
          name: graphql-schema
          path: services/site/schema.gql

      - name: Test
        run: npm run test:coverage --prefix services/site

      - name: Upload Coverage
        uses: actions/upload-artifact@v4
        with:
          name: test-coverage-site
          path: services/site/coverage

  build-site:
    needs:
      - variables
      - lint-site
      - test-site
      - generate-graphql-schema
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    outputs:
      digest: ${{ steps.build.outputs.digest }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: graphql-schema
          path: services/site/schema.gql

      - name: Build
        id: build
        uses: ./.github/actions/docker-build
        with:
          path: services/site
          npm-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: site
          version: ${{ needs.variables.outputs.environment-name }}
          registry-user: ${{ github.actor }}
          registry-password: ${{ secrets.GITHUB_TOKEN }}

  upload-coverage-reports:
    needs:
      - test-site
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Determine git commit sha and branch because github actions does not provide them in a consistent manner
        id: git-variables
        env:
          PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        run: |
          if [[ "$GITHUB_EVENT_NAME" = "pull_request" ]]; then
            GIT_COMMIT_SHA=$PR_HEAD_SHA
            GIT_BRANCH=$GITHUB_HEAD_REF
          else
            GIT_COMMIT_SHA=$GITHUB_SHA
            GIT_BRANCH=${GITHUB_REF#"refs/heads/"}
          fi

          echo "git-branch=$GIT_BRANCH" >> "$GITHUB_OUTPUT"
          echo "git-commit-sha=$GIT_COMMIT_SHA" >> "$GITHUB_OUTPUT"

      - name: Download CodeClimate Test Reporter
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter

      - name: Download Site test coverage
        uses: actions/download-artifact@v4
        with:
          name: test-coverage-site
          path: services/site/coverage/

        env:
          GIT_BRANCH: ${{ steps.git-variables.outputs.git-branch }}
          GIT_COMMIT_SHA: ${{ steps.git-variables.outputs.git-commit-sha }}

      - name: Format Site Coverage
        run: |
          cd services/site
          ./../../cc-test-reporter format-coverage -t lcov --add-prefix services/site -o coverage/codeclimate.json coverage/lcov.info
        env:
          GIT_BRANCH: ${{ steps.git-variables.outputs.git-branch }}
          GIT_COMMIT_SHA: ${{ steps.git-variables.outputs.git-commit-sha }}

      - name: Sum Coverage
        run: ./cc-test-reporter sum-coverage services/*/coverage/codeclimate.json -p 2
        env:
          GIT_BRANCH: ${{ steps.git-variables.outputs.git-branch }}
          GIT_COMMIT_SHA: ${{ steps.git-variables.outputs.git-commit-sha }}

      - name: Upload Coverage
        run: ./cc-test-reporter upload-coverage
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE_TEST_REPORTER_ID }}
          GIT_BRANCH: ${{ steps.git-variables.outputs.git-branch }}
          GIT_COMMIT_SHA: ${{ steps.git-variables.outputs.git-commit-sha }}

  test-end-to-end:
    needs:
      - variables
      - build-site
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18.15.0
          cache: npm
          registry-url: https://npm.pkg.github.com/
          scope: '@a11yphant'
          cache-dependency-path: tests/package-lock.json

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Site Image Artifact
        uses: actions/download-artifact@v4
        with:
          name: site-image
          path: /tmp/site-image/

      - name: Load Site Image
        run: docker load --input /tmp/site-image/image.tar

      - name: Start services
        run: docker compose -f docker-compose.yml -f docker-compose.tests.yml up -d --quiet-pull --wait --no-color
        env:
          IMAGE_TAG: ${{ needs.variables.outputs.environment-name }}

      - name: Migrate Database
        run: docker compose -f docker-compose.yml -f docker-compose.tests.yml exec site npm run prisma:migrate:prod

      - name: Seed Database
        run: docker compose -f docker-compose.yml -f docker-compose.tests.yml exec site npm run console:prod import:challenges

      - name: Run Cypress
        uses: cypress-io/github-action@v4
        with:
          working-directory: tests
          install-command: npm ci
          command: npm test
          build: npm run db-dump:update
        env:
          CYPRESS_BASE_URL: "http://localhost:3001"

      - name: Upload artifact
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: tests/cypress/screenshots/
          retention-days: 1

      - name: Echo Site Logs
        if: failure()
        run: docker compose -f docker-compose.yml -f docker-compose.tests.yml logs site --no-color --tail all

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: tests/cypress/screenshots
          retention-days: 1

  publish-site-image:
    needs:
      - variables
      - test-end-to-end
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    outputs:
      image-digest: ${{ steps.publish.outputs.digest }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Publish Image
        id: publish
        uses: ./.github/actions/docker-push-image-from-artifact
        with:
          artifact-name: site-image
          image: ghcr.io/a11yphant/site:${{ needs.variables.outputs.environment-name }}
          registry-user: ${{ github.actor }}
          registry-password: ${{ secrets.GITHUB_TOKEN }}
