name: CI/CD

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - develop

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  # ESLint Config
  lint-eslint-config:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        uses: ./.github/workflows/prepare.yml
        with:
          path: packages/eslint-config

      - name: Lint
        run: npm run lint --prefix packages/eslint-config

  # API
  generate-graphql-schema:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - name: Prepare
        uses: ./.github/workflows/prepare.yml
        with:
          path: services/api

      - name: Generate GraphQL Schema
        run: npm run generate-schema --prefix services/api

      - uses: actions/upload-artifact@v3
        with:
          name: graphql-schema
          path: services/api/schema.gql
          retention-days: 1

  lint-api:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - name: Prepare
        uses: ./.github/workflows/prepare.yml
        with:
          path: services/api

      - name: Lint
        run: npm run lint --prefix services/api

  test-api:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: a11yphant
          POSTGRES_USER: a11yphant
          POSTGRES_PASSWORD: secret
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Prepare
        uses: ./.github/workflows/prepare.yml
        with:
          path: services/api

      - name: Test
        run: npm run test:coverage --prefix services/api
        env:
          DB_URL: postgresql://a11yphant:secret@localhost:5432/a11yphant

  # Site
  lint-site:
    needs: generate-graphql-schema
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - name: Prepare
        uses: ./.github/workflows/prepare.yml
        with:
          path: services/site

      - uses: actions/download-artifact@v3
        with:
          name: graphql-schema
          path: services/api/schema.gql

      - name: Lint
        run: npm run lint --prefix services/site

  test-site:
    needs: generate-graphql-schema
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - name: Prepare
        uses: ./.github/workflows/prepare.yml
        with:
          path: services/site

      - uses: actions/download-artifact@v3
        with:
          name: graphql-schema
          path: services/api/schema.gql

      - name: Test
        run: npm run test:coverage --prefix services/site