name: Deploy Preview

on:
  workflow_call:

env:
  NEON_DATABASE_USERNAME: ${{ secrets.NEON_DATABASE_USERNAME }}
  NEON_API_KEY: ${{ secrets.NEON_API_KEY }}
  NEON_PROJECT_ID: ${{ secrets.NEON_PROJECT_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  BRANCH_NAME: preview/pr-${{ github.event.number }}-${{ github.head_ref || github.ref_name }}

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: ./.github/actions/prepare-node

      - name: Create Neon Branch
        id: create-branch
        uses: neondatabase/create-branch-action@v5
        with:
          project_id: ${{ env.NEON_PROJECT_ID }}
          branch_name: ${{ github.ref == 'refs/heads/main' && 'preview/main' || env.BRANCH_NAME }}
          username: ${{ env.NEON_DATABASE_USERNAME }}
          api_key: ${{ env.NEON_API_KEY }}
          database: "a11yphant"

      - name: Run Migrations
        run: |
            touch .env

            echo DATABASE_URL=${{ steps.create-branch.outputs.db_url_with_pooler }}?sslmode=require >> .env
            echo DATABASE_URL_UNPOOLED=${{ steps.create-branch.outputs.db_url }}?sslmode=require >> .env

            npm run db:generate
            npm run db:migrate:prod

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ env.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --token=${{ env.VERCEL_TOKEN }}

      - name: Deploy Preview to Vercel
        id: deploy
        run: echo preview_url=$(vercel deploy --prebuilt --token=${{ env.VERCEL_TOKEN }}) >> $GITHUB_OUTPUT

      - name: Add domain alias
        id: alias
        env:
          SUBDOMAIN: pr-${{ github.event.number }}
        run: |
          vercel alias --token=${{ env.VERCEL_TOKEN }} set ${{ steps.deploy.outputs.preview_url }} ${{ github.ref == 'refs/heads/main' && 'beta' || env.SUBDOMAIN }}-a11yphant.vercel.app
          echo domain=https://${{ github.ref == 'refs/heads/main' && 'beta' || env.SUBDOMAIN }}-a11yphant.vercel.app >> $GITHUB_OUTPUT

      - name: Comment on Pull Request
        if: ${{ github.ref != 'refs/heads/main' }}
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Vercel Preview URL :rocket: : ${{ steps.alias.outputs.domain }}
            Neon branch :elephant: : https://console.neon.tech/app/projects/${{ env.NEON_PROJECT_ID }}/branches/${{ steps.create-branch.outputs.branch_id }}
