name: Destroy Review App

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed

jobs:
  variables:
    runs-on: ubuntu-22.04
    outputs:
      environment-name: ${{ steps.variables.outputs.environment-name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Variables
        uses: ./.github/actions/variables
        id: variables

  destroy-review-app:
    runs-on: ubuntu-22.04
    needs:
      - variables
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.INFRASTRUCTURE_REPOSITORY_DISPATCH }}
          repository: a11yphant/infrastructure
          event-type: destroy-review-app
          client-payload: |
            {
              "environment-name": "${{ needs.variables.outputs.environment-name }}"
            }
