name: Destroy Review App

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed

jobs:
  variables:
    runs-on: ubuntu-22.04
    outputs:
      environment-name: ${{ steps.environment-name.outputs.environment-name }}
    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4

      - run: echo "environment-name=${{ env.GITHUB_REF_SLUG }}" >> $GITHUB_OUTPUT
        id: environment-name

  destroy-review-app:
    runs-on: ubuntu-22.04
    needs:
      - variables
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.INFRASTRUCTURE_REPOSITORY_DISPATCH }}
          repository: a11yphant/infrastructure
          event-type: destroy-review-app
          client-payload: |
            {
              "environment-name": "${{ needs.variables.outputs.environment-name }}"
            }
