name: ESLint Config Publish

on:
  push:
    tags:
      - eslint-config-v*

jobs:
  publish-eslint-config:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/
          scope: '@a11yphant'

      - name: NPM Publish
        run: cd packages/eslint-config && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
